# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(659, 972)
        self.label = QLabel(MainWindow)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 40, 241, 21))
        self.lineEditTasa = QLineEdit(MainWindow)
        self.lineEditTasa.setObjectName(u"lineEditTasa")
        self.lineEditTasa.setGeometry(QRect(280, 40, 231, 20))
        self.label_2 = QLabel(MainWindow)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 70, 101, 31))
        self.lineEditUmbral = QLineEdit(MainWindow)
        self.lineEditUmbral.setObjectName(u"lineEditUmbral")
        self.lineEditUmbral.setGeometry(QRect(140, 80, 151, 20))
        self.line = QFrame(MainWindow)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 30, 41, 251))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(MainWindow)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(610, 30, 41, 251))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(MainWindow)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(30, 170, 601, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(MainWindow)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(30, 20, 601, 20))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label_3 = QLabel(MainWindow)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 100, 81, 41))
        self.lineEditPesos = QLineEdit(MainWindow)
        self.lineEditPesos.setObjectName(u"lineEditPesos")
        self.lineEditPesos.setGeometry(QRect(130, 110, 261, 20))
        self.label_4 = QLabel(MainWindow)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(390, 110, 221, 21))
        self.line_5 = QFrame(MainWindow)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(610, 270, 41, 271))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(MainWindow)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(10, 270, 41, 271))
        self.line_6.setFrameShape(QFrame.VLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(MainWindow)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(30, 310, 601, 20))
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(MainWindow)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 220, 101, 31))
        self.label_7 = QLabel(MainWindow)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 250, 81, 31))
        self.label_8 = QLabel(MainWindow)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 190, 241, 31))
        self.label_9 = QLabel(MainWindow)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(230, 140, 121, 31))
        self.lineEditTasa2 = QLineEdit(MainWindow)
        self.lineEditTasa2.setObjectName(u"lineEditTasa2")
        self.lineEditTasa2.setGeometry(QRect(270, 200, 231, 20))
        self.lineEditUmbral2 = QLineEdit(MainWindow)
        self.lineEditUmbral2.setObjectName(u"lineEditUmbral2")
        self.lineEditUmbral2.setGeometry(QRect(140, 230, 131, 20))
        self.lineEditPesos2 = QLineEdit(MainWindow)
        self.lineEditPesos2.setObjectName(u"lineEditPesos2")
        self.lineEditPesos2.setGeometry(QRect(130, 260, 201, 20))
        self.line_7 = QFrame(MainWindow)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(610, 500, 41, 271))
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_9 = QFrame(MainWindow)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(30, 450, 601, 20))
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_10 = QFrame(MainWindow)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(10, 500, 41, 271))
        self.line_10.setFrameShape(QFrame.VLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.label_10 = QLabel(MainWindow)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(200, 280, 121, 31))
        self.label_12 = QLabel(MainWindow)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 330, 241, 31))
        self.label_13 = QLabel(MainWindow)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(40, 390, 81, 31))
        self.label_14 = QLabel(MainWindow)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(40, 360, 101, 31))
        self.label_15 = QLabel(MainWindow)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(210, 430, 121, 31))
        self.lineEditTasa3 = QLineEdit(MainWindow)
        self.lineEditTasa3.setObjectName(u"lineEditTasa3")
        self.lineEditTasa3.setGeometry(QRect(280, 340, 221, 20))
        self.lineEditUmbral3 = QLineEdit(MainWindow)
        self.lineEditUmbral3.setObjectName(u"lineEditUmbral3")
        self.lineEditUmbral3.setGeometry(QRect(140, 370, 141, 20))
        self.lineEditPeso3 = QLineEdit(MainWindow)
        self.lineEditPeso3.setObjectName(u"lineEditPeso3")
        self.lineEditPeso3.setGeometry(QRect(120, 400, 191, 20))
        self.line_11 = QFrame(MainWindow)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(30, 610, 601, 20))
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.label_17 = QLabel(MainWindow)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 470, 241, 31))
        self.label_18 = QLabel(MainWindow)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(40, 530, 81, 31))
        self.label_19 = QLabel(MainWindow)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(40, 500, 101, 31))
        self.lineEditTasa4 = QLineEdit(MainWindow)
        self.lineEditTasa4.setObjectName(u"lineEditTasa4")
        self.lineEditTasa4.setGeometry(QRect(280, 480, 211, 20))
        self.lineEditUmbral4 = QLineEdit(MainWindow)
        self.lineEditUmbral4.setObjectName(u"lineEditUmbral4")
        self.lineEditUmbral4.setGeometry(QRect(140, 510, 161, 20))
        self.lineEditPeso4 = QLineEdit(MainWindow)
        self.lineEditPeso4.setObjectName(u"lineEditPeso4")
        self.lineEditPeso4.setGeometry(QRect(120, 540, 181, 20))
        self.label_20 = QLabel(MainWindow)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(180, 570, 121, 31))
        self.label_21 = QLabel(MainWindow)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(190, 730, 121, 31))
        self.label_22 = QLabel(MainWindow)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(40, 630, 241, 31))
        self.label_23 = QLabel(MainWindow)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(50, 660, 101, 31))
        self.label_25 = QLabel(MainWindow)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(50, 690, 81, 31))
        self.line_12 = QFrame(MainWindow)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(30, 760, 601, 20))
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.lineEditTasa5 = QLineEdit(MainWindow)
        self.lineEditTasa5.setObjectName(u"lineEditTasa5")
        self.lineEditTasa5.setGeometry(QRect(280, 640, 191, 20))
        self.lineEditUmbral5 = QLineEdit(MainWindow)
        self.lineEditUmbral5.setObjectName(u"lineEditUmbral5")
        self.lineEditUmbral5.setGeometry(QRect(150, 670, 151, 20))
        self.lineEditPeso5 = QLineEdit(MainWindow)
        self.lineEditPeso5.setObjectName(u"lineEditPeso5")
        self.lineEditPeso5.setGeometry(QRect(130, 700, 201, 20))
        self.pushButtonIniciar = QPushButton(MainWindow)
        self.pushButtonIniciar.setObjectName(u"pushButtonIniciar")
        self.pushButtonIniciar.setGeometry(QRect(240, 800, 151, 51))
        self.label_5 = QLabel(MainWindow)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(340, 260, 221, 21))
        self.label_11 = QLabel(MainWindow)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(330, 540, 221, 21))
        self.label_16 = QLabel(MainWindow)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(320, 400, 221, 21))

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"191209-MATUZ TAMAYO", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">TASA DE APRENDIZAJE: </span></p></body></html>", None))
        self.lineEditTasa.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">UMBRAL:</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">PESOS:</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">SEPARADO POR COMAS POR FAVOR</span></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">UMBRAL:</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">PESOS:</span></p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">TASA DE APRENDIZAJE: </span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; text-decoration: underline;\">GRAFICADO 1</span></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; text-decoration: underline;\">GRAFICADO 2</span></p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">TASA DE APRENDIZAJE: </span></p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">PESOS:</span></p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">UMBRAL:</span></p></body></html>", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; text-decoration: underline;\">GRAFICADO 3</span></p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">TASA DE APRENDIZAJE: </span></p></body></html>", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">PESOS:</span></p></body></html>", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">UMBRAL:</span></p></body></html>", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; text-decoration: underline;\">GRAFICADO 4</span></p></body></html>", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; text-decoration: underline;\">GRAFICADO 5</span></p></body></html>", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">TASA DE APRENDIZAJE: </span></p></body></html>", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-style:italic;\">UMBRAL:</span></p></body></html>", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-style:italic;\">PESOS:</span></p></body></html>", None))
        self.pushButtonIniciar.setText(QCoreApplication.translate("MainWindow", u"INICIAR", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">SEPARADO POR COMAS POR FAVOR</span></p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">SEPARADO POR COMAS POR FAVOR</span></p></body></html>", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">SEPARADO POR COMAS POR FAVOR</span></p></body></html>", None))
    # retranslateUi

